### ISSUE TITLE
Calling OSC commands from GDSCripts

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#14]
What's the proper way to call an OSC command that needs a `sender` as argument from GDScript?  Should it send an OSC message to itself?  I had this in prior iterations, but I'm sure there's a proper way to do it.

A use for this is loading custom command files and running them at startup, for example with config files (#12 )

**Comment by totalgee** [comment]
I think the proper way, if the functionality doesn't really require a sender, would be to refactor the "inner functionality" (as I did in the case of getting the anim asset path) to be a normal method.  Then have an OSC method call that inner method. But in general this shouldn't be needed too much between "normal" OSC commands, since everything should be done via defs. If you need lower-level functionality, expose a method that does that, and then wrap the OSC version with a different method...I think.

**Comment by loopier** [comment]
Ah, right, that's actually how I had it in my last OF iteration.  I implemented this in all methods which made the code a bit redundant, but exposing just the needed ones looks like a great approach.

**Comment by loopier** [comment]
The answer is: use `$Main.evalOscCommand(address, args, null)`. Note that `sender` is set to `null`.
From within an actor node, `$Main` can't be used, but it can be accessed with `get_parent().get_parent()` (sic: it's 2 levels above)
