### ISSUE TITLE
`res://` path doesn't work with compiled executable

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#16]
When running the exported binary, the `res://` path is not the same and cannot find resources.  I haven't tried to figure out what the path is.

**Comment by totalgee** [comment]
It should be relative to the location of the executable. At least it was when I tried it on Windows...

**Comment by totalgee** [comment]
I just investigated this a bit (on Windows, but it should be similar on Linux).

An exported executable uses a `.pck` or `.zip` file for its asset library, and when doing so, it won't find a separate `animations/` directory (or `commands/`, `config/`, ...) -- we are kind of going against what is normally done in Godot projects with our runtime-loaded assets. To make it work, you can either extract the `.zip` file (so the executable is in the same directory as the `project.godot` file, or you can compress your `animations/` and other custom resource directories *inside* the zip file.

Also, there is currently a bug that it won't use the zip file (even if it should)...see [here](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html#pck-versus-zip-pack-file-formats) for more info. You can make it work using a script that does this:

`$ ./animatron --main-pack animatron.zip`

So -- it won't work with a `.pck` file, but it *will* work with an extracted `.zip` file (basically the normal project directory structure, except with compiled scripts and optimized assets) or if you add your custom asset directories into the zip file.

Note that you also need to have the `libgdosc` shared library (`.dll` or `.so`) in the same directory as the executable.

**Comment by loopier** [comment]
Would absolute paths work?  Maybe we could set a default directory in the `/config` def and put everything there.  Could resources then be added at runtime?

**Comment by totalgee** [comment]
I've revamped the way all file/directory handling is done, so that relative or asset paths will now resolve as expected (relative to the project location, and no longer have to be embedded in the zip or pck file) when running in-editor or in exported executables:

`/load/defs myDefs.osc` -> will load `commands/myDefs.osc` under project folder
`/load/config myConfig.osc` -> will load `config/myConfig.osc` under project folder
`/assets/path more_anims` -> will set animation path to `more_anims/` under project folder

Also, now absolute paths can be used:

`/load/defs /some/absolute/myDefs.osc`
`/load/config /another/abs/config.osc`
`/assets/path C:/Users/someone/Documents/anims`

- Revamp runtime file/directory handling to work with exported app ec58456

**Comment by totalgee** [comment]
(BTW, it will still try to load `commands/init.osc` and `config/config.osc` at startup, under the project directory.)
