### ISSUE TITLE
Recursive OSC for message composition

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#2]
Any OSC message should be mapped to either a Godot function, another OSC message or a combination of both.  A structure I tested that works is something like this:
```
var cmds = {
	"/play": funcref($OscInterface, "playAnim"), # a Godot function 
	"/create": funcref($OscInterface, "createAnim"), # a Godot function 
	"/create-n-play" : [
		{"address": "/create", "params": "runner"},
		{"address": "/play", "params": "runner"},
		]
	}

func exectue(msg):
        var cmd = cmds.find[msg]
	if cmd == oscMsg:
                # recursively call this function until it runs Godot functions
		for msgs in cmd:
			execute(cmd)
	else:
		# call mapped Godot function

```

**Comment by totalgee** [comment]
Summary of chat conversation on this topic:

Glen F, [20.10.21 12:03]
Started working on a custom OSC command language. First in-progress commit 95f0950 pushed.

Glen F, [20.10.21 12:04]
Here's an example of what I'd like it to do, let me know if this seems acceptable (note how one custom command can call another):

```
def /startup
    /load om-walk-*
    /wait 2
    /create walker om-walk-s
    /color walker 0.7 0.2 0.1
    /crowd
    /wait 3
    /say walker "Hi everybody!"

def /createsel actor anim
    /create $actor $anim
    /select $actor

def /crowd
    /deselect
    /createsel om1 om-walk-w
    /createsel om2 om-walk-w
    /createsel om3 om-walk-w
    /createsel om4 om-walk-w
    /createsel om5 om-walk-w
    /group crowd om?
```

Roger P, [20.10.21 12:19]
mmm... the idea is very very cool

Roger P, [20.10.21 12:20]
but I'm not sure about defining another syntax different from OSC itself

Glen F, [20.10.21 12:20]
What do you mean, different from OSC itself?

Roger P, [20.10.21 12:20]
the cool thing about the system I set up is that you don't have to learn anything, it's just plain OSC

Glen F, [20.10.21 12:21]
But OSC is not a text file format... You mean arrays, like in SC?

Roger P, [20.10.21 12:21]
[In reply to Glen F]
that your example would need a syntax parser.  I know it's not much different than a simple text parser, but I reckon it would easily become complicated

Glen F, [20.10.21 12:21]
There's nothing to learn except "def"

Roger P, [20.10.21 12:21]
[In reply to Glen F]
haha, so far

Glen F, [20.10.21 12:22]
It doesn't parse anything except "def". The rest are just OSC command addresses and arguments.

Glen F, [20.10.21 12:22]
We can skip arguments if desired, I thought that would be cool so you could really extend it like macros.

Roger P, [20.10.21 12:22]
[In reply to Glen F]
I know, but why not use an array?  or just another OSC message, something like:
`/def "/customcommand" arg1 arg2 ... argN`

Glen F, [20.10.21 12:22]
(I mean custom "def" arguments, like `actor anim` in the example)

Roger P, [20.10.21 12:23]
You have given it more thought than me, I hadn't gotten this far

Glen F, [20.10.21 12:23]
[In reply to Roger P]
Oh, okay, that would be fine. But why is it "simpler" or better?

Roger P, [20.10.21 12:23]
because it's an OSC command itself

Glen F, [20.10.21 12:24]
Okay, so the idea is to define everything via OSC? (I thought you were using text files before)...that's fine, we can support that.

Roger P, [20.10.21 12:24]
maybe I didn't explain my idea well: all we would need is one function that reads OSC messages and maps to either a language func (whatever language it is) or another OSC message array

Roger P, [20.10.21 12:25]
[In reply to Glen F]
text files are just one way to store macros

Glen F, [20.10.21 12:25]
It will be a bit clunky because the ordering/timing is important. I mean, it's "stateful", because you'd have to start defining a command, then send all the commands, then stop defining. But should be okay if you send as bundles.

Roger P, [20.10.21 12:25]
I'm not sure I get this

Roger P, [20.10.21 12:26]
but, as I said,  I haven't given it enough thought

Glen F, [20.10.21 12:27]
```
/def /newcommand blah blah
/addtodef /load om-walk-n
/addtodef /wait 4
/addtodef /create omo om-walk-n
/enddef /newcommand
```

(or something like that, you mean?)

Roger P, [20.10.21 12:27]
when I have a moment I'd like to sketch an idea of what I have in mind

Glen F, [20.10.21 12:28]
What I have is basically just the start to load/parse a CSV file, etc, and start to build a map of custom commands. But it's all tentative and can be changed, there's nothing "wasted" there.

Roger P, [20.10.21 12:28]
I think more something like
```
/newcommand [
   /load om-walk-n,
  /wait 4,
  /create omo om-walk-n,
]
```

Glen F, [20.10.21 12:29]
(instead of comma-separate it's space-separated, which makes it very natural to parse, and if you need spaces in your string arguments you just add quotes)

Roger P, [20.10.21 12:29]
[In reply to Glen F]
sounds good

Glen F, [20.10.21 12:29]
And no need for commas, etc, to reduce typing when live coding.

Roger P, [20.10.21 12:29]
[In reply to Glen F]
cool

Glen F, [20.10.21 12:34]
[In reply to Roger P]
I haven't given it that much thought either. I just looked at your examples from earlier projects (https://github.com/loopier/clip/blob/master/examples/commands-example.clc), and thought of how to "simplify" it (or so I thought 😉). Your array syntax could also work, but I like to potentially support argument names at some point (like macro parameters), I think it would make it much more powerful.

Roger P, [20.10.21 12:36]
```
cmds = {
    "load": load(msg),
    "wait": wait(msg),
    "create": create(msg),
    "newcommand": [ "load", "/wait",  "/create"]
}

def parseOsc(msg):
    addr = msg.addr
    args = msg.args
    cmd = cmds[addr]
    if type(cmd) == OscMsg:
        parseOsc(msg)
    else:
        callFunc(cmd)
```

Roger P, [20.10.21 12:37]
[In reply to Glen F]
right, that's where I hadn't gone yet.  I think macro parameters would be a great thing, too

Roger P, [20.10.21 12:37]
[In reply to Roger P]
this is my idea

Roger P, [20.10.21 12:37]
but, as you said, needs macro arguments

Glen F, [20.10.21 12:40]
[In reply to Roger P]
That's also what my thing would do. It will parse the data file (or however you want to specify the name, args and list of sub-commands) and add it to the dictionary of custom cmds, similar to what you show above.

Glen F, [20.10.21 12:43]
Another option would be to write the "custom commands" in GDScript, and load/run it on demand. I think that should be possible. Then it really would look more like what you have above, but it's also more likely to crash your program if you have typos or errors in it at runtime.

**Comment by totalgee** [comment]
Roger P, [20.10.21 13:04]
Do you have an example of output?

Glen F, [20.10.21 13:06]
For the example file I used above, it parses to this:

**Command: /startup**
```
{args:[], cmds:[
    [/load, om-walk-*],
    [/wait, 2],
    [/create, walker, om-walk-s],
    [/color, walker, 0.7, 0.2, 0.1],
    [/crowd],
    [/wait, 3],
    [/say, walker, Hi everybody!]]}
```
**Command: /createsel**
```
{args:[actor, anim], cmds:[
    [/create, $actor, $anim],
    [/select, $actor]]}
```
**Command: /crowd**
```
{args:[], cmds:[
    [/deselect],
    [/createsel, om1, om-walk-w],
    [/createsel, om2, om-walk-w],
    [/createsel, om3, om-walk-w],
    [/createsel, om4, om-walk-w],
    [/createsel, om5, om-walk-w],
    [/group, crowd, om?]]}
```

**Comment by totalgee** [comment]
Roger P, [20.10.21 13:12]
looks great!

Roger P, [20.10.21 13:14]
I'm not so sure there's a "right thing".  But yes, I'm all for discussing ideas, as long as we don't get stuck in the discussion

Glen F, [20.10.21 13:17]
Yes. Anyhow, as long as you can define (recursively) custom OSC messages which contain lists of sub-messages, that's the main thing. You can add to the "dictionary" of them in other ways, we can also have an OSC command `/defcmd` or something to create one on the fly. Maybe something like:

`/defcmd "/dosomething", "/create fox fox-walk", "/color fox 1 0 0", "/position fox 0.5 0.5"`

Roger P, [20.10.21 13:19]
sounds amazing!

**Comment by totalgee** [comment]
All the basics are working. See:

- First working version of custom commands (similar to macros) f3d93b8 
- Add `/defcmd` to define a custom OSC command a64ce27
- Work in progress: initial support for `/wait` command in sub-commands 2a3ab60
- Rename `/defcmd` to `/def`; convert `/position` args to float 6410e6c
- Add `/load/defs` command; document `/def`, `/load/defs` and `/wait` commands f530f5f
