### ISSUE TITLE
Should we add a `?` suffix to randomize command values?

### ISSUE THREAD

**Issue by loopier** [loopier/animatron-godot3#27]
As we already do with the `!` suffix, we could add a `?` optional suffix in commands to randomize the value of that command. The argument values could then be used as `min` and `max`:
`/scale? anactor 0.5 1.5` would be the same as doing `x.("/scale", "anactor",  rrand(0.5,1.5))` in supercollider. 

This would be specially useful with groups, avoiding the need iterate over its members in the client side.

A caveat is that there's no way of setting different random values for `x`and `y`, this would only work in proportional `scale` (and `position`), and wouldn't work with `color`, for example.

A possible solution to make it more general is to have hardcoded defaults that would be used if no arguments are passed.

**Comment by totalgee** [comment]
I don't know...because of the issue you mention, i.e. the confusing "double meaning" of multiple arguments (normally one `/scale` arg means uniform scale, two means separate x and y).

If this is important -- to have it choose the random number on the Animatron side rather than the OSC client side -- maybe an argument (string) parsing scheme could be used. As an example (not to implement, just to get the idea): "?(0.1,0.5)" or "r/0.1/0.5" or "[0.1,0.5]". Not sure this is a good idea, we'd want to think careful about what syntax would make sense. Then the argument number/position for different OSC commands would stay exactly the same as it is now. And the randomization could easily be supported by *any* commands we want, without making their code more complicated.

**Comment by loopier** [comment]
How about optional argument syntax like `min?max` . For example:

- `/scale anactor 0.5?1.5 0.25?0.75` for random `x` and `y`
- `/scale anactor 0.5?1.5` for random uniform
- `/color anactor 0.5?1.0 0 0` for random `red` value but fixed `green` and `blue` values
- `/frame anactor ?` or `/frame anactor 0?inf`

Your wildcard system is just for actor/group names, isn't it? Would this be compatible with it? Although it might add a bit of confusion. I don't know, I'd have to think a bit more about it.

I agree that we should carefully think about this, to keep it consistent with what we already have and aiming at keeping it simple. Now it's VERY flexible and powerful, and simple enough to make it quite intuitive (at least for me). I constantly find new ways to do complex stuff with what we have. It's a creative booster :)

**Comment by loopier** [comment]
This has been solved in bfde283962bec3d8c2d8a3c8f1fdaba411ffd4f3
